### ISSUE TITLE
Support deep Structure Parameters

### ISSUE THREAD

**Issue by cerker** [hibersap/hibersap#14]
As of yet, Hibersap only supports flat structure and table parameters, i.e. ABAP structures that contain only simple field parameters. This is a restriction for the BAPI standard and thus work well in most cases.
However, in the real world, there are ABAP function modules that have deep structures, i.e. structure or table parameters containing other structure or table parameters and so on.
The Hibersap mapping mechanism shall be extended to support these kinds of deep structures.

**Comment by SciLor** [comment]
Patch is incomplete
Generating the classes crashes when there are deep structures:

`Exception in thread "main" java.lang.IllegalStateException: Trying to access row values in a table  which does not have any rows yet
	at com.sap.conn.jco.rt.AbstractRecord.checkRowCapacity(AbstractRecord.java:930)
	at com.sap.conn.jco.rt.AbstractRecord.getStructure(AbstractRecord.java:2572)
	at com.sap.conn.jco.rt.AbstractRecord.getStructure(AbstractRecord.java:53)
	at com.sap.conn.jco.rt.AbstractField.getStructure(AbstractField.java:362)
	at org.hibersap.generation.bapi.ReverseBapiMapper.getParameterMapping(ReverseBapiMapper.java:96)
	at org.hibersap.generation.bapi.ReverseBapiMapper.addFieldMappings(ReverseBapiMapper.java:137)
	at org.hibersap.generation.bapi.ReverseBapiMapper.getParameterMapping(ReverseBapiMapper.java:101)
	at org.hibersap.generation.bapi.ReverseBapiMapper.mapFields(ReverseBapiMapper.java:78)
	at org.hibersap.generation.bapi.ReverseBapiMapper.map(ReverseBapiMapper.java:60)
	at org.hibersap.generation.HibersapGenerator.generate(HibersapGenerator.java:43)`

**Comment by jaecktec** [comment]
Is there a solution yet?

Because for me this looks like a sap jco problem.. and I'd rly like to have the deep structures feature.

as a workaround you could add a row to the table or check if you can cast it to a JCoTable?

(I'm currently not able to test this)

**Comment by lyca** [comment]
I just checked in a patch for the generation of classes with deep structures.
