### ISSUE TITLE
ReverseBapiMapper 

### ISSUE THREAD

**Issue by aymenhouissa** [hibersap/hibersap#41]
Hi,
I'm trying the maven plugin [https://github.com/hurzelpurzel/hibersap-maven-plugin](url) to generate SAP entities,
I've got the following exception, it looks like trying to read an empty table ! am i wrong ?

`Caused by: java.lang.IllegalStateException: Trying to access row values in an empty table which does not have any rows
	at com.sap.conn.jco.rt.AbstractRecord.checkRowCapacity(AbstractRecord.java:997)
	at com.sap.conn.jco.rt.AbstractRecord.getTable(AbstractRecord.java:2686)
	at com.sap.conn.jco.rt.AbstractRecord.getTable(AbstractRecord.java:48)
	at com.sap.conn.jco.rt.AbstractField.getTable(AbstractField.java:352)
	at org.hibersap.generation.bapi.ReverseBapiMapper.getParameterMapping(ReverseBapiMapper.java:98)
	at org.hibersap.generation.bapi.ReverseBapiMapper.addFieldMappings(ReverseBapiMapper.java:134)
	at org.hibersap.generation.bapi.ReverseBapiMapper.getParameterMapping(ReverseBapiMapper.java:98)
	at org.hibersap.generation.bapi.ReverseBapiMapper.addFieldMappings(ReverseBapiMapper.java:134)
	at org.hibersap.generation.bapi.ReverseBapiMapper.getParameterMapping(ReverseBapiMapper.java:93)
	at org.hibersap.generation.bapi.ReverseBapiMapper.addFieldMappings(ReverseBapiMapper.java:134)
	at org.hibersap.generation.bapi.ReverseBapiMapper.getParameterMapping(ReverseBapiMapper.java:93)
	at org.hibersap.generation.bapi.ReverseBapiMapper.mapFields(ReverseBapiMapper.java:76)
	at org.hibersap.generation.bapi.ReverseBapiMapper.map(ReverseBapiMapper.java:56)
	at org.hibersap.plugin.GenerateEntitiesMojo.processSearch(GenerateEntitiesMojo.java:109)
	at org.hibersap.plugin.GenerateEntitiesMojo.execute(GenerateEntitiesMojo.java:95)`

**Comment by cerker** [comment]
Hi, unfortunately, the ReverseBapiMapper isn't very well maintained. At one point we needed it for the JBoss Forge plugin, but the developer who implemented this stopped doing it, also because at that time the Forge project was rather a moving target and difficult to keep up with.
Having that said, I like very much that you are actually developing an alternative to the Forge plugin. 
I guess your problem is that the ReverseBapiMapper may not support "deep parameters", i.e. a structure or table with a table in it. While we implemented this feature some time ago (initially Hibersap supported only flat structures/tables), I think the ReverseBapiMapper was not adopted to this. If you are willing to analyse and fix this, you are of course welcome to send a pull request.
If you prefer to own the code generation in your own project, since it may be easier for you to maintain, you can also use the existing code as a starting point and copy it to your project. And maybe send a PR later when you feel comfortable with the code.
